/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d5e3fc",
        "primary-container": "#0052ff",
        "tertiary-container": "#5e667d",
        "on-tertiary-fixed": "#131b2e",
        "tertiary": "#464e64",
        "on-surface-variant": "#434656",
        "on-primary-container": "#dfe3ff",
        "outline-variant": "#c3c5d9",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#dae2fd",
        "on-primary-fixed": "#001452",
        "tertiary-fixed-dim": "#bec6e0",
        "primary-fixed-dim": "#b7c4ff",
        "surface-container": "#eceef0",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadc",
        "primary": "#003ec7",
        "on-background": "#191c1e",
        "inverse-primary": "#b7c4ff",
        "on-secondary-fixed": "#0d1c2e",
        "secondary": "#515f74",
        "on-tertiary-container": "#dde4ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#3f465c",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#d5e3fc",
        "surface-tint": "#004ced",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#57657a",
        "outline": "#737688",
        "on-primary-fixed-variant": "#0038b6",
        "on-secondary-fixed-variant": "#3a485b",
        "surface-container-highest": "#e0e3e5",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#b9c7df",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#191c1e"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
};
